### ISSUE TITLE
Update to version 2.8.0

### ISSUE THREAD

**Issue by ariefabubakar** [NAXAM/fscalendar-ios-binding#2]
Thank you and good job on the binding. Can you update it to the latest version please? https://github.com/WenchaoD/FSCalendar/releases . The latest version is 2.8.0

**Comment by tipa** [comment]
In the meantime v2.8.1 was published. I second the wish to have updated bindings :)

**Comment by tipa** [comment]
Thanks for the efforts, but it seems like I can't compile my app any more now, am I doing anything wrong?
![image](https://user-images.githubusercontent.com/2863198/73556626-134b5d00-4450-11ea-8e47-10ea5bd591ad.png)

**Comment by fleuverouge** [comment]
Hi @tipa,
Can you please try with the package version 2.8.1.1?

**Comment by tipa** [comment]
Looking good now, thanks a lot!
